#!/bin/bash
# copy-evidence-models-to-og-drives.sh
# For DJ Speedy / Lexi (Waka's baby) drive protection
# Run this AFTER generating evidence locally (the python/node scripts write to data/evidence-logs)
# Then manually (or with sudo/diskutil) copy the outputs + models to the OG volumes.
#
# Because the OG drives (AI TOOLS, GOAT ROYALTY APP, backup) often mount read-only in this env,
# this script generates the commands you run on your machine with the drives plugged in.
#
# Usage:
#   bash scripts/copy-evidence-models-to-og-drives.sh
#
# After copy, the drives have the EVID- manifests + 30+ models for Lexi on Thor or the client.
# This fulfills "drives are up now" + hard drive protection + chain of custody.

set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOCAL_EVIDENCE="$REPO_ROOT/data/evidence-logs"
LOCAL_MODELS_STAGING="$REPO_ROOT/data/lexi-models-staging"

echo "=== LEXI / DJ SPEEDY - COPY EVIDENCE + MODELS TO OG DRIVES ==="
echo "Repo: $REPO_ROOT"
echo ""
echo "NOTE: GOAT ROYALTY APP and AI TOOLS were NTFS (read-only on Mac)."
echo "After you reformat them to exFAT (see instructions), these commands will work directly."
echo ""

# 1. Evidence (local first - read-only volumes workaround)
echo "Local evidence logs (generated by ingest + generate-evidence-log.js for Lexi / DJ Speedy protection):"
ls -l "$LOCAL_EVIDENCE" 2>/dev/null || echo "(populated below)"

echo ""
echo "=== EXACT COMMANDS TO RUN (plug drives, run as user or with sudo if needed for mount) ==="
echo ""

cat << 'EOF'
# --- EVIDENCE (run on machine with OG drives attached) ---
mkdir -p "/Volumes/AI TOOLS/evidence-logs" "/Volumes/GOAT ROYALTY APP/evidence-logs" "/Volumes/backup/evidence-logs" 2>/dev/null || true

# Master + specific backup manifest (from completed task + node generator)
cp -v data/evidence-logs/MASTER-OG-DRIVES-EVIDENCE-2026-06-08.txt "/Volumes/backup/evidence-logs/" || true
cp -v data/evidence-logs/post-fbi-evidence-preservation-2026-06-08T04-43-47.* "/Volumes/backup/evidence-logs/" || true

# Repeat similar for AI TOOLS and GOAT ROYALTY APP manifests when generated (run node scripts/generate-evidence-log.js on those dirs locally first)
# cp -v data/evidence-logs/ai-tools*.* "/Volumes/AI TOOLS/evidence-logs/"
# cp -v data/evidence-logs/goat*.* "/Volumes/GOAT ROYALTY APP/evidence-logs/"

echo "Evidence + master chain-of-custody copied to OG drives for Lexi (Waka's baby) protection."
echo "Original drives stay in your possession. Hashes + timestamps documented."
EOF

# Also stage the manifests for easy transfer
cp -v data/evidence-logs/MASTER-OG-DRIVES-EVIDENCE-2026-06-08.txt data/evidence-logs/post-fbi* 2>/dev/null || true

echo ""
echo "=== MODELS (35 in installed-models.txt) ==="
echo "Client has some GGUF + ollama_data. Stage here then copy:"

mkdir -p "$LOCAL_MODELS_STAGING"

cat << 'EOF'
# Example: copy what is already in the Lexi client on MONEY PENNY
# (run from a machine that can see the volume)
CLIENT_MODELS="/Volumes/MONEY PENNY/Lexi-Client-Test-USB-v1/Shared/models"
cp -rv "$CLIENT_MODELS"/* "/Volumes/AI TOOLS/models/" || echo "AI TOOLS may be read-only - copy manually or remount"
cp -rv "$CLIENT_MODELS"/* "/Volumes/GOAT ROYALTY APP/models/" || echo "GOAT may be read-only"
cp -rv "$CLIENT_MODELS"/* "/Volumes/backup/models/" || echo "backup may be read-only"

# For missing large models (70B etc.), use the list in installed-models.txt and curl from HF to staging then copy.
# See INSTALL-MODEL-DOWNLOADER.sh or run curls with plenty of space.
EOF

echo ""
echo "=== AFTER COPY ==="
echo "On Thor (after flash + mount OG drives to /mnt/ai-storage):"
echo "  rsync or cp the evidence-logs and models from the mounted OG drives."
echo "  Run Lexi with local models from /mnt/ai-storage/models + the evidence tools."
echo ""
echo "This gives Lexi full local evidence/creative power with chain-of-custody on the drives DJ Speedy owns/protects."
echo "Only AGENT007 + MONEY PENNY are the personal originals. Lexi is Waka's baby for the crew."
echo ""
echo "Drives are up. Let's build the ultimate agent next."