#!/usr/bin/env bash
# ============================================================
# Local Offline LLM Setup — GOAT Force Edition
# Adapted from Oscar Edition for DJ Speedy's i2i 1 drive setup
#
# Model store:  /Volumes/i2i 1/Agent-007-GOAT/Shared/models/ollama_data
# Ollama home:  /Users/be100radio/Library/Application Support/Agent007Runtime/ollama
# Ollama port:  11435  (GOAT Force dedicated port)
#
# Usage:
#   ./setup-local-llm-oscar.sh [--pull-defaults] [--status]
# ============================================================

set -euo pipefail

# ── GOAT Force paths ──────────────────────────────────────────
OSCAR_ROOT="${OSCAR_ROOT:-/Volumes/i2i 1/Agent-007-GOAT}"
OLLAMA_MODELS="${OLLAMA_MODELS:-$OSCAR_ROOT/Shared/models/ollama_data}"
OLLAMA_HOME="${OLLAMA_HOME:-/Users/be100radio/Library/Application Support/Agent007Runtime/ollama}"
OLLAMA_PORT="${OLLAMA_PORT:-11435}"
OLLAMA_HOST="127.0.0.1:$OLLAMA_PORT"
OLLAMA_API="http://$OLLAMA_HOST"
BIN_DIR="$OSCAR_ROOT/Shared/bin"
LOG_DIR="$OSCAR_ROOT/logs"

PULL_DEFAULTS=false
SHOW_STATUS=false
for arg in "$@"; do
  case "$arg" in
    --pull-defaults) PULL_DEFAULTS=true ;;
    --status)        SHOW_STATUS=true ;;
    --help|-h)
      cat <<'EOF'
Usage: setup-local-llm-oscar.sh [--pull-defaults] [--status] [--help]

  --pull-defaults   Pull GOAT Force default FAST-tier model set after setup
  --status          Show Ollama status and list models, then exit

Env overrides:
  OSCAR_ROOT    Override i2i 1 drive root
  OLLAMA_PORT   Ollama port (default: 11435)
  OLLAMA_MODELS Override model store path
EOF
      exit 0 ;;
  esac
done

log()  { printf "[goat-llm-setup] %s\n" "$*"; }
die()  { printf "[goat-llm-setup] ERROR: %s\n" "$*" >&2; exit 1; }
ok()   { printf "[goat-llm-setup] ✅  %s\n" "$*"; }
warn() { printf "[goat-llm-setup] ⚠️   %s\n" "$*" >&2; }

# ── Detect OS / arch ──────────────────────────────────────────
case "$(uname -s)" in
  Darwin) OS="darwin" ;;
  Linux)  OS="linux"  ;;
  *) die "Unsupported OS: $(uname -s)" ;;
esac
case "$(uname -m)" in
  x86_64|amd64)  ARCH="amd64"  ;;
  arm64|aarch64) ARCH="arm64"  ;;
  *) die "Unsupported arch: $(uname -m)" ;;
esac

# ── Status mode ───────────────────────────────────────────────
if [[ "$SHOW_STATUS" == true ]]; then
  log "GOAT Force Ollama status:"
  log "  OLLAMA_HOST   : $OLLAMA_HOST"
  log "  OLLAMA_MODELS : $OLLAMA_MODELS"
  if curl -fsS --max-time 5 "$OLLAMA_API/api/tags" >/dev/null 2>&1; then
    ok "Ollama is online at $OLLAMA_API"
    curl -fsS "$OLLAMA_API/api/tags" | python3 -c "
import json,sys
data=json.load(sys.stdin)
models=data.get('models',[])
print(f'  {len(models)} models loaded:')
for m in models: print('  -', m['name'])
" 2>/dev/null || curl -fsS "$OLLAMA_API/api/tags"
  else
    warn "Ollama NOT running on $OLLAMA_API"
    log "Start with: OLLAMA_MODELS=\"$OLLAMA_MODELS\" OLLAMA_HOST=$OLLAMA_HOST ollama serve"
  fi
  exit 0
fi

log "==================================================="
log "       GOAT Force Local LLM Setup"
log "==================================================="
log "i2i 1 root   : $OSCAR_ROOT"
log "Ollama port  : $OLLAMA_PORT"
log "Model store  : $OLLAMA_MODELS"
log "Ollama home  : $OLLAMA_HOME"
log ""

# ── Create required directories ───────────────────────────────
mkdir -p "$OLLAMA_MODELS" "$OLLAMA_HOME/runners" "$OLLAMA_HOME/tmp" \
         "$BIN_DIR" "$LOG_DIR" 2>/dev/null || true

# ── Find or install Ollama ────────────────────────────────────
find_ollama() {
  for candidate in \
    "$BIN_DIR/ollama-darwin" \
    "$BIN_DIR/ollama" \
    "$(command -v ollama 2>/dev/null || true)"
  do
    [[ -n "$candidate" && -x "$candidate" ]] && { echo "$candidate"; return 0; }
  done
  return 1
}

OLLAMA_BIN=""
if OLLAMA_BIN="$(find_ollama)"; then
  ok "Found Ollama: $OLLAMA_BIN"
else
  log "Ollama not found. Installing..."
  if command -v brew >/dev/null 2>&1; then
    brew install ollama
    OLLAMA_BIN="$(command -v ollama)"
  else
    log "Downloading Ollama binary for macOS ${ARCH}..."
    curl -fsSL -o "$BIN_DIR/ollama-darwin" \
      "https://github.com/ollama/ollama/releases/latest/download/ollama-darwin"
    chmod +x "$BIN_DIR/ollama-darwin"
    OLLAMA_BIN="$BIN_DIR/ollama-darwin"
    ok "Ollama downloaded to $OLLAMA_BIN"
  fi
fi

# ── Write GOAT Force Ollama env file ─────────────────────────
ENV_FILE="/Users/be100radio/GOAT-Royalty-App/.goat-ollama.env"
cat > "$ENV_FILE" <<EOF
# Auto-generated by setup-local-llm-oscar.sh — GOAT Force Edition
export OLLAMA_MODELS="$OLLAMA_MODELS"
export OLLAMA_HOME="$OLLAMA_HOME"
export OLLAMA_RUNNERS_DIR="$OLLAMA_HOME/runners"
export OLLAMA_TMPDIR="$OLLAMA_HOME/tmp"
export OLLAMA_HOST="$OLLAMA_HOST"
export OLLAMA_PROXY_TARGET="$OLLAMA_API"
export OSCAR_MODEL_DOWNLOAD_PORT="$OLLAMA_PORT"
export OLLAMA_ORIGINS="*"
export OLLAMA_NO_PRUNE=1
EOF
ok "GOAT Ollama env written to $ENV_FILE"
log "  Source it with:  . $ENV_FILE"

# ── Start Ollama if not already running ───────────────────────
if curl -fsS --max-time 5 "$OLLAMA_API/api/tags" >/dev/null 2>&1; then
  ok "Ollama is already running at $OLLAMA_API"
else
  log "Starting Ollama (port $OLLAMA_PORT)..."
  export OLLAMA_MODELS OLLAMA_HOST
  export OLLAMA_RUNNERS_DIR="$OLLAMA_HOME/runners"
  export OLLAMA_TMPDIR="$OLLAMA_HOME/tmp"
  export OLLAMA_ORIGINS="*"
  HOME="$OLLAMA_HOME" "$OLLAMA_BIN" serve > "$LOG_DIR/ollama.log" 2>&1 &
  OLLAMA_PID=$!
  log "Ollama PID: $OLLAMA_PID  Log: $LOG_DIR/ollama.log"
  log "Waiting for Ollama (up to 60s)..."
  for i in $(seq 1 60); do
    curl -fsS --max-time 3 "$OLLAMA_API/api/tags" >/dev/null 2>&1 && { ok "Ollama ready at $OLLAMA_API"; break; }
    sleep 1
    [[ "$i" -eq 60 ]] && warn "Ollama did not become ready in 60s. Check: $LOG_DIR/ollama.log"
  done
fi

# ── FAST tier default models ──────────────────────────────────
DEFAULT_MODELS=(
  "llama3.2:3b"
  "phi3:mini"
  "nemotron-mini:4b"
  "gemma3:4b"
  "nomic-embed-text"
)

if [[ "$PULL_DEFAULTS" == true ]]; then
  log "Pulling GOAT Force FAST-tier models..."
  for model in "${DEFAULT_MODELS[@]}"; do
    log "Pulling $model ..."
    OLLAMA_HOST="$OLLAMA_HOST" "$OLLAMA_BIN" pull "$model" \
      && ok "$model pulled" \
      || warn "$model pull failed — retry: OLLAMA_HOST=$OLLAMA_HOST $OLLAMA_BIN pull $model"
  done
else
  log "Skipping model pulls (pass --pull-defaults to pull FAST tier)."
fi

log ""
log "==================================================="
ok "GOAT Force local LLM setup complete!"
log ""
log "  Ollama API  : $OLLAMA_API"
log "  Models dir  : $OLLAMA_MODELS (56 models)"
log "  Log         : $LOG_DIR/ollama.log"
log ""
log "Quick-start:"
log "  Chat:     OLLAMA_HOST=$OLLAMA_HOST $OLLAMA_BIN run llama3.1:70b"
log "  API test: curl $OLLAMA_API/api/tags"
log "  Intel:    http://127.0.0.1:5500"
log "  Web app:  http://127.0.0.1:8090"
log "==================================================="
